name: repository dispatch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1.1.2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: small-teams-behind-enemy-lines/redacted
          event-type: project-update-event
